# Q3 Using Scikit-Learn

In [2]:
import numpy as np
import pandas as pd
import time
import gc
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [3]:
# Change to your GA Tech ID
ga_id = 'aeissa3'
# Requires a print() statement do not modify below print statement
print(ga_id)

aeissa3


# Q3.1 Data Import and Cleansing Setup

In [4]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set. We've started this for you. 
# XXX

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('./pulsar_stars.csv', header =0)
# -------------------------------

# XXX
# TODO: Separate out the x_data and y_data. We've started this for you.
# XXX

# -------------------------------
# ADD CODE HERE
x_data = data.loc[:, ["X1","X2", "X3","X4","X5","X6","X7","X8",]]
y_data = data.loc[:, "y"]

x_data = np.array(x_data)
y_data = np.array(y_data)


# -------------------------------


In [5]:
# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' 
# set to 614.
# 

# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.7, random_state=614, shuffle = True)
# -------------------------------

# Q3.2 Linear Regression 

In [6]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
reg = LinearRegression().fit(X_train, y_train)

# -------------------------------

In [7]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
predict_train = reg.predict(X_train)
predict_train = np.rint(predict_train)
accuracy_train = accuracy_score(predict_train, y_train)
print (accuracy_train)
# Requires a print() statement
# -------------------------------

0.9701992922331906


In [8]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
predict_test = reg.predict(X_test)
predict_test = np.rint(predict_test)
accuracy_test = accuracy_score(predict_test, y_test)
print (accuracy_test)
# -------------------------------

0.9712666613456781


# Q3.3 Random Forest Classifier

In [9]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# Set 'random_state' to 614
# XXX

# -------------------------------
# ADD CODE HERE
rfc = RandomForestClassifier( random_state=614)
rfc.fit(X_train, y_train)
# -------------------------------

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=614,
                       verbose=0, warm_start=False)

In [10]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX


# -------------------------------
# ADD CODE HERE
# Requires a print() statement
rfc_y_train = rfc.predict(X_train)
rfc_train_accuracy = accuracy_score(rfc_y_train, y_train)
print(rfc_train_accuracy)
# -------------------------------

1.0


In [11]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

rfc_y_test = rfc.predict(X_test)
rfc_test_accuracy = accuracy_score(rfc_y_test, y_test)
print(rfc_test_accuracy)
# -------------------------------

0.9800462926011653


## Q3.3.1 Feature Importance

In [12]:
# XXX
# TODO: Determine the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE

importances = rfc.feature_importances_
print(importances)
# Requires a print() statement
# -------------------------------

[0.21807625 0.05054945 0.30306858 0.19663864 0.07661864 0.05270494
 0.05353238 0.04881113]


In [13]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

indices = np.argsort(importances)[::-1]
print(indices)

# -------------------------------

[2 0 3 4 6 5 1 7]


## Q3.3.2 Hyper-parameter Tuning

In [26]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# 'n_estimators': [4, 16, 256]
# 'max_depth': [2, 8, 16]
# XXX

# -------------------------------
# ADD CODE HERE
params = {'n_estimators': [4, 16, 256], 'max_depth': [2, 8, 16]}
gsv1 = SVC()
clf = GridSearchCV(rfc, paramgsv1result = clf.fit(X_trat# -------------------------------
------------

SyntaxError: unexpected EOF while parsing (<ipython-input-26-ff8922caa976>, line 12)

In [23]:
# XXX
# TODO: Get the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

best_prams = result.best_params_
print(best_prams)
# -------------------------------

NameError: name 'result' is not defined

In [16]:
# XXX
# TODO: Get the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
best_score = result.best_score_
print(best_score)
# -------------------------------

NameError: name 'result' is not defined

# Q3.4 Support Vector Machine

## Q3.4.1 Pre-process

In [17]:
# XXX
# TODO: Pre-process the data to standardize it, otherwise the grid search will take much longer.
# XXX

# -------------------------------
# ADD CODE HERE
scaler = StandardScaler()
scaler.fit(X_train)
scaler.transform(X_train)
scaler.transform(X_test)
# -------------------------------

array([[-0.16175365, -0.9644018 ,  0.06265245, ...,  0.18414715,
        -0.83656696, -0.77515386],
       [ 1.20180584,  0.35724345, -0.89571726, ..., -0.80130843,
         1.66427933,  1.98876323],
       [ 0.806827  ,  4.00489069, -0.51405268, ...,  1.90798933,
        -1.67708537, -0.98874076],
       ...,
       [ 0.17875585, -0.28919239, -0.18930314, ..., -0.39594736,
        -0.09223792, -0.32833401],
       [ 0.36985502, -0.20126808, -0.34037183, ..., -0.16606109,
        -0.22323198, -0.43618497],
       [-0.39393305,  0.51950781, -0.04276922, ..., -0.92550528,
         4.20847387,  6.75347452]])

## Q3.4.2 Classification

In [18]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
clf = SVC(gamma='auto')
clf.fit(X_train, y_train)
# -------------------------------

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
clf_train = clf.predict(X_train)
clf_train_accuracy = accuracy_score(clf_train, y_train)
print (clf_train_accuracy)
# -------------------------------

0.9938536040230955


In [20]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

clf_test = clf.predict(X_test)
clf_test_accuracy = accuracy_score(clf_test, y_test)
print(clf_test_accuracy)
# -------------------------------

0.9093303535796952


## Q3.4.3 Hyper-parameter Tuning

In [21]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# 'kernel':('linear', 'rbf') 
# 'C':[0.01, 0.1, 1.0]
# XXX

# -------------------------------
# ADD CODE HERE

params = {'kernel':('linear', 'rbf') , 'C':[0.01, 0.1, 1.0]}
gsv2 = GridSearchCV(clf, params, n_jobs=-1, return_train_score=True)
result2= gsv2.fit(X_train, y_train)
# -------------------------------

In [27]:
# XXX
# TODO: Get the best score, using .best_score_.
# Note: Set n_jobs=-1 and return_train_score=True
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

best_score2 = result2.best_score_
print(best_score2)

# -------------------------------

{'C': 1.0, 'kernel': 'linear'}
0.978581258970394


In [30]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and standardization. 
# XXX

clf = SVC(gamma='auto', C= 1.0, kernel='linear')
clf.fit(X_train, y_train)
hyper_training = clf.predict(X_train)
hyper_test = clf.predict(X_test)

# -------------------------------
# ADD CODE HERE
# -------------------------------

In [31]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

hyper_training_accuracy = accuracy_score(hyper_training, y_train)
print(hyper_training_accuracy)
# -------------------------------

0.9782082324455206


In [34]:
# XXX
# TODO: Test its accuracy (on the test set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
hyper_test_accuracy = accuracy_score(hyper_test, y_test)
print(hyper_test_accuracy)

# -------------------------------

0.9794077739644026


## Q3.4.4 Cross Validation Results 

In [35]:
# XXX
# TODO: Get the rank test score for all hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

print(gsv2.cv_results_['rank_test_score'])
# -------------------------------

[3 4 2 4 1 4]


In [0]:
# XXX
# TODO: Get the mean testing score for all of hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX
# -------------------------------
# ADD CODE HERE
# Requires a print() statement

print(gsv2.cv_results_['mean_test_score'])
# -------------------------------

# Q3.5 PCA

In [0]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# NOTE: Use the full x data set for this section 'x_data'

# -------------------------------
# ADD CODE HERE
# You should see an output here of PCA(copy=True....)
# -------------------------------

In [0]:
# XXX
# TODO: Get percentage of variance explained by each of the selected components
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------

In [0]:
# XXX
# TODO: Get the singular values corresponding to each of the selected components.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------